config/routes.rb
Omawho::Application.routes.draw do
  resources :events, :except => :show do
    post 'attend' => 'events#attend', :as => :attend
    put 'approve' => 'events#approve', :as => :approve
  end
  
  match 'why' => 'users#why', :as => :why
  match 'beta' => 'users#beta', :as => :beta
  
  match 'profile' => 'users#edit', :as => :profile
  
  resources :images, :except => :show

  resources :password_resets
  resources :user_sessions
  resources :users, :except => :show
  
  match 'add' => 'users#new', :as => :signup
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'event/:event' => 'users#index', :as => :event
  match 'category/:category' => 'users#index', :as => :category
  
  match '/feed' => 'users#feed', :as => :feed, :defaults => {:format => 'atom'}
  root :to => 'users#index'
  
  match ':username' => 'users#show', :as => :view_profile
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :username, :email, :password, :password_confirmation, :name, :twitter, :website, :bio, :image_id, :category, :facebook, :pinterest, :linkedin, :github, :googleplus, :dribbble, :company

  CATEGORIES = {"web_software" => "Web & Software", "graphic_design" => "Graphic Design", "architecture_interior_design" => "Architecture & Interior Design", "photography" => "Photography", "music_film_art" => "Music/Film/Art", "fashion" => "Fashion", "writing" => "Writing", "vc" => "Venture Capital", "community" => "Community Connector", "non_profit" => "Non-Profit"}

  scope :random, order("RANDOM()")

  validates_presence_of :username
  validates_presence_of :category
  validates_presence_of :email
  validates_presence_of :name
  validates :email, :format => { :with => /@/ }
  validates :username, :format => { :with => /^(\w|-)*$/, :message => "can only contain letters, numbers, underscores, and dashes" }
  validates :website, :format => { :with => /^http/ }, :allow_blank => true
  validates_exclusion_of :username, :in => %w(category login logout add profile quiz beta)
  validates_inclusion_of :category, :in => CATEGORIES.map{|k,v| k}
  validates_uniqueness_of :username
  validates_uniqueness_of :email
  validates_length_of :bio, :within => 0..140
  validates_length_of :password, :within => 4..99, :allow_blank => :allow_blank_password

  validates :image_id, :presence => true

  belongs_to :image

  has_and_belongs_to_many :events

  def allow_blank_password
    !new_record?
  end

  def linkedin_url
    format_social_link(linkedin, "linkedin.com", "http://linkedin.com/in/$USERNAME")
  end

  def facebook_url
    format_social_link(facebook, "facebook.com", "http://facebook.com/$USERNAME")
  end

  def twitter_url
    format_social_link(twitter.gsub(/^@/, ""), "twitter.com", "http://twitter.com/$USERNAME")
  end

  def dribbble_url
    format_social_link(dribbble, "dribbble.com", "http://dribbble.com/$USERNAME")
  end

  def github_url
    format_social_link(github, "github.com", "http://github.com/$USERNAME")
  end

  def pinterest_url
    format_social_link(pinterest, "pinterest.com", "http://pinterest.com/$USERNAME")
  end

protected
  def format_social_link(input, domain, example)
    # If "domain" is present, they probably added the whole URL.
    if input =~ /#{domain}/

      # If it starts with a valid protocol, use the link as is.
      if input =~ /^https?:\/\//
        input

      # If just the protocol is absent, add it.
      elsif input =~ /^((www\.)|(#{domain}))/
        "http://#{input}"

      # Otherwise I don't know what the fuck is going on.
      else
        input
      end

    # Sane people just used their username.
    else
      "#{example.gsub("$USERNAME", input)}"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :except => [:edit, :update, :destroy]
  
  def feed
    @feed_title = "#{@site_title}"
    @feed_items = User.order("created_at DESC")

    # Feed's update timestamp:
    @updated = @feed_items.first.created_at unless @feed_items.empty?

    respond_to do |format|
      format.atom { render :layout => false }

      # Redirect RSS permanently to ATOM.
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end
  
  # GET /users
  # GET /users.json
  def index
    User.connection.execute "select setseed(#{cookies[:random_seed]})"
    
    # Event -------------------------------------------------------------------
    if params[:event].present?
      gallery_event
    
    # Category ----------------------------------------------------------------
    elsif params[:category].present? && User::CATEGORIES[params[:category]].present?
      gallery_category
    
    # Home --------------------------------------------------------------------
    else
      gallery_home
    end
    
    # -------------------------------------------------------------------------
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
      format.js
    end
  end
  
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_username(params[:username])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    if current_user
      @user = current_user
      
      if @user.image
        @image = @user.image
      else
        @image = Image.new
      end
    else
      not_authenticated
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @image = Image.new

    respond_to do |format|
      if @user.save
        auto_login(@user)
        format.html { redirect_to(:root, :notice => 'Thanks for adding your profile.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = current_user
    @image = @user.image

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to :profile, notice: 'Your profile has been updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = current_user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to :logout }
      format.json { head :no_content }
    end
  end
  
private

  def gallery_home
    @page_title = "The Faces of #{@site_location}'s Creative Community"
    @page_description = "#{@site_title} shows basic profiles of the designers, programmers, decorators, photographers and other creatives in #{@site_location}."
    
    if params[:page].blank? || params[:page] == 1
      @gallery_type = "home"
    else
      @gallery_type = "page"
    end
    
    @users = User.random.page(params[:page]).per_page(12)
    
    active_categories = User.uniq.pluck(:category)
    @active_categories = User::CATEGORIES.select {|k,v| active_categories.include?(k)}
  end
  
  def gallery_category
    @page_title = "The Faces of #{@site_location}'s Creative Community - #{User::CATEGORIES[params[:category]]}"
    @page_description = "#{@site_title} shows basic profiles of the designers, programmers, decorators, photographers and other creatives in #{@site_location}."
    
    if params[:page].blank? || params[:page] == 1
      @gallery_type = "category"
    else
      @gallery_type = "page"
    end

    @users = User.random.where(:category => params[:category]).page(params[:page]).per_page(12)
    
    active_categories = User.uniq.pluck(:category)
    @active_categories = User::CATEGORIES.select {|k,v| active_categories.include?(k)}
  end
  
  def gallery_event
    @event = Event.find_by_slug(params[:event])
    
    if @event.approved?
      show_event = true
    elsif current_user && current_user.admin?
      show_event = true
    else
      show_event = false
    end
    
    if show_event
      if params[:page].blank? || params[:page] == 1
        @gallery_type = "event"
      else
        @gallery_type = "page"
      end
      
      @page_title = "Who's Attending #{@event.name}"     
      @page_description = "#{@site_location} creatives who are attending #{@event.name} on #{@event.date.to_s(:full)}."
      @blurb = "Put faces to names at #{@event.name}"
      
      # If category is also set:
      if params[:category].present? && User::CATEGORIES[params[:category]].present?
        @users = User.random.where(:id => @event.user_ids, :category => params[:category]).page(params[:page]).per_page(12)
      else
        @users = User.random.where(:id => @event.user_ids).page(params[:page]).per_page(12)
      end
      
      active_event_categories = @event.users.pluck(:category)
      @active_categories = User::CATEGORIES.select {|k,v| active_event_categories.include?(k)}
    else
      redirect_to :events
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@image, :html => {:multipart => true, :id => "upload_profile_photo"}, :remote => true) do |f| %>
  <div id="upload_profile_photo_container">
    <div class="pull-left">
      <%= image_tag((@user.image ? @user.image.file.square : "theme/user-avatar.jpg"), :alt => "This is you! (?)", :id => "profile_photo_preview", :class => "img-polaroid") %>
    </div>
    
    <div class="pull-left">
      <div id="profile_photo_before">
        <%= f.file_field :file, :id => "profile_photo_field" %>
        <%= f.submit "Upload", :style => "display: none" %>
      </div>
      <div id="profile_photo_after" style="display: none">
        <%= image_tag("loading.gif", :alt => "Loading...") %>
      </div>
      <div id="profile_photo_success" style="display: none">
        <i class="icon-ok"></i>
      </div>
    </div>
  </div>
<% end %>

<%= form_for(@user, :html => {:id => "user_form"}) do |f| %>
  <%= f.hidden_field :image_id, :id => "profile_photo_id" %>
  
  <%= form_errors @user, "Profile" %>
  
  <div class="row">
    <div class="span5">
      <div class="profile_fields">
        <div class="input-prepend">
          <span class="add-on"><i class="icon-user"></i></span>
          <%= f.text_field :name, :placeholder => "Full Name", :class => "input-xlarge" %>
        </div>
        
        <div class="input-prepend">
          <span class="add-on"><i class="icon-heart"></i></span>
          <%= f.text_field :username, :placeholder => "Username", :class => "input-xlarge" %>
        </div>

        <div class="input-prepend">
          <span class="add-on"><i class="icon-envelope"></i></span>
          <%= f.text_field :email, :placeholder => "Email", :class => "input-xlarge" %>
        </div>

        <div class="input-prepend">
          <span class="add-on"><i class="icon-lock"></i></span>
          <%= f.password_field :password, :placeholder => "Password", :class => "input-xlarge" %>
        </div>
        
        <div class="input-prepend">
          <span class="add-on"><i class="icon-certificate"></i></span>
          <%= f.select :category, User::CATEGORIES.map {|k,v| [v, k]}, :include_blank => "Choose a category." %>
        </div>
      </div>
      
      <div class="profile_fields">
        <p>Add your web presence and bio. All fields are optional.</p>
        
        <div class="input-prepend">
          <span class="add-on"><i class="icon-suitcase"></i></span>
          <%= f.text_field :company, :placeholder => "Company", :class => "input-xlarge" %>
        </div>
        
        <div class="input-prepend">
          <span class="add-on"><i class="icon-twitter"></i></span>
          <%= f.text_field :twitter, :placeholder => "Twitter", :class => "input-xlarge" %>
        </div>
        
        <div class="input-prepend">
          <span class="add-on"><i class="icon-facebook"></i></span>
          <%= f.text_field :facebook, :placeholder => "Facebook", :class => "input-xlarge" %>
        </div>
        
        <div class="input-prepend">
          <span class="add-on"><i class="icon-github"></i></span>
          <%= f.text_field :github, :placeholder => "Github", :class => "input-xlarge" %>
        </div>
        
        <div class="input-prepend">
          <span class="add-on"><i class="icon-asterisk"></i></span>
          <%= f.text_field :dribbble, :placeholder => "Dribbble", :class => "input-xlarge" %>
        </div>
        
        <div class="input-prepend">
          <span class="add-on"><i class="icon-pinterest"></i></span>
          <%= f.text_field :pinterest, :placeholder => "Pinterest", :class => "input-xlarge" %>
        </div>
        
        <div class="input-prepend">
          <span class="add-on"><i class="icon-linkedin"></i></span>
          <%= f.text_field :linkedin, :placeholder => "LinkedIn", :class => "input-xlarge" %>
        </div>

        <div class="input-prepend">
          <span class="add-on"><i class="icon-globe"></i></span>
          <%= f.text_field :website, :placeholder => "Website", :class => "input-xlarge" %>
        </div>
      </div>
      
      <div class="profile_fields">
        <div>
          <%= f.text_area :bio, :placeholder => "Bio", :class => "span4", :rows => 3, :maxlength => 140 %>
        </div>
      </div>
      
      <%= f.submit "Submit", :disabled => (@user.image ? false : true), :class => "btn btn-inverse", :id => "submit_add_form" %>
    </div>
  </div>
<% end %>

app/views/users/_user_gallery.html.erb
<% @users.each do |user| %>
  <li class="span3 gallery-item" data-id="id-<%= user.id %>" data-type="<%= user.category %>">
    <% if user.image %>
      <%= link_to image_tag(user.image.file.square, :alt => user.name), view_profile_path(user.username), :class => "quiz_link" %>
    <% else %>
      <%= link_to image_tag("default_pic.jpg", :alt => user.name), view_profile_path(user.username), :class => "quiz_link" %>
    <% end %>
    
    <span class="project-details">
      <%= link_to user.name, view_profile_path(user.username), :class => "user_name" %>
      <%= User::CATEGORIES[user.category] %>
    </span>
  </li>
<% end %>

app/views/users/_user_gallery_container.html.erb
<div class="row clearfix">
  <ul class="gallery-post-grid holder" id="user_gallery_list">
    <%= render :partial => "user_gallery" %>
  </ul>
</div>

<div id="append_and_paginate">
  <%= will_paginate @users %>
</div>

app/views/users/beta.html.erb
<!-- Page Content
================================================== --> 
<div class="row">
  <div class="span8">
    <p>I often forget a person's name when I see them at events.</p>
    
    <p>Maybe flipping through <%= @site_title %> in the parking lot before the event will help me avoid awkward moments and introductions.</p>

    <p>I also think it'll be fun to see everyone's mugs in one place.</p>

    <p>Go ahead and add yourself if you want and poke around a bit. It's such a basic tool right now that you won't need any longer than it took you to read these words.</p>
    
    <p>If you have feedback, shoot it to <a href="mailto:sumeet@bigwheelbrigade.com">sumeet@bigwheelbrigade.com</a>.</p>
    
    <h4>Thanks for helping!<br /><br />&mdash; Sumeet</h4>
  </div>
</div><!-- End container row -->

<style type="text/css" media="screen">
  p{
    font-size: 18px;
    line-height: 1.5;
  }
</style>

app/views/users/edit.html.erb
<% @page_title = "Edit Your Face" %>
<% @page_description = "Edit your profile on #{@site_title}." %>

<h1>Your profile</h1>

<%= render :partial => "form" %>

<div>
  <hr />
  <p><%= link_to 'Delete your profile', @user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></p>
</div>

app/views/users/index.html.erb
<div class="row" id="user_gallery">
  <div class="span12 gallery">
    <% if @event %>
      <h4 id="event_header"><%= @event.name %></h4>
      <h5>
        <%= @event.date.to_s(:full) %><br />

        <% if @event.venue.present? %>
          <%= @event.venue %><br />
        <% end %>

        <span class="event_city muted"><%= @event.location %></span>
      </h5>

      <% if !current_user %>
        <p><%= link_to "Sign in to mark your attendance.", login_path(:return_to_url => event_path(@event.slug)), :class => "btn btn-primary btn-mini" %></p>
      <% end %>

      <% if current_user && @event.is_current %>
        <%= form_tag event_attend_path(@event.id) do %>
          <% if @event.link.present? %>
            <%= link_to "Event Website", @event.link, :class => "btn btn-mini" %>
          <% end %>&nbsp;

          <% if current_user.events.exists?(@event) %>
            <%= button_tag "Cancel Your Attendance", :type => "submit", :class => "btn btn-danger btn-mini" %>
          <% else %>
            <%= button_tag "Attend", :type => "submit", :class => "btn btn-primary btn-mini" %>
          <% end %>
        <% end %>
      <% end %>

      <hr />
    <% end %>

    <h4 id="quiz_header" class="inactive">&nbsp;<i class="icon-bolt"></i> <span>Activate Quiz Mode</span></h4>

    <ul id="filterOptions" class="gallery-cats clearfix">
      <% if @event %>
        <li id="category_filter_all" class="active"><%= link_to "All", root_path(:event => @event.slug), :class => "all" %></li> 
      <% else %>
        <li id="category_filter_all" class="active"><%= link_to "All", :root, :class => "all" %></li> 
      <% end %>

      <% @active_categories.each do |k, v| %>
        <% if @event %>
          <li id="category_filter_<%= k %>"><%= link_to v, category_path(k, :event => @event.slug), :class => k %></li>
        <% else %>
          <li id="category_filter_<%= k %>"><%= link_to v, category_path(k), :class => k %></li>
        <% end %>
      <% end %>
    </ul>
    
    <div id="user_gallery_container">
      <%= render :partial => "user_gallery_container" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% @page_title = "Add Your Face" %>
<% @page_description = "Add yourself to #{@site_title}'s gallery of creative faces. It's free." %>

<h1>Add your face &#9786;</h1>

<br />

<%= render :partial => "form" %>

app/views/users/show.html.erb
<% @page_title = "#{@user.name}" %>
<% @page_description = @user.bio.present? ? @user.bio : "#{@user.name}'s profile on #{@site_title}." %>

<div class="row">
  <div class="span12 gallery-single">

    <div class="row">
      <div class="span6">
        <% if @user.image %>
          <%= image_tag @user.image.file.square, :alt => @user.name, :class => "thumbnail" %>
        <% else %>
          <%= image_tag "default_pic.jpg", :alt => @user.name, :class => "thumbnail" %>
        <% end %>
      </div>
      <div class="span6">
        <h2>
          <%= @user.name %>
          
          <% if @user.twitter.present? %>
            <a href="https://twitter.com/<%= @user.twitter %>" class="twitter-follow-button" data-show-count="false" data-dnt="true">Follow @<%= @user.twitter %></a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
          <% end %>
        </h2>

        <% if @user.company.present? %>
          <h4><%= @user.company %></h4>
        <% end %>
        
        <h5 class="muted"><%= User::CATEGORIES[@user.category] %></h5>
        <p class="lead"><%= @user.bio %></p>

        <ul class="project-info">
          <% if @user.twitter.present? %>
            <li>
             <h6><i class="icon-twitter"></i> Twitter:</h6> <%= link_to "@#{@user.twitter}", @user.twitter_url %>
            </li>
          <% end %>
          
          <% if @user.facebook.present? %>
            <li><h6><i class="icon-facebook"></i> Facebook:</h6> <%= link_to @user.facebook, @user.facebook_url %></li>
          <% end %>
          
          <% if @user.github.present? %>
            <li>
              <h6><i class="icon-github"></i> Github:</h6> <%= link_to @user.github, @user.github_url %>
              
              <!--iframe src="http://ghbtns.com/github-btn.html?user=<%= @user.github %>&type=follow"
                allowtransparency="true" frameborder="0" scrolling="0" width="132" height="20" class="github_follow_button"></iframe-->
            </li>
          <% end %>
          
          <% if @user.dribbble.present? %>
            <li><h6><i class="icon-asterisk"></i> Dribbble:</h6> <%= link_to @user.dribbble, @user.dribbble_url %></li>
          <% end %>
          
          <% if @user.pinterest.present? %>
            <li><h6><i class="icon-pinterest"></i> Pinterest:</h6> <%= link_to @user.pinterest, @user.pinterest_url %></li>
          <% end %>
          
          <% if @user.linkedin.present? %>
            <li><h6><i class="icon-linkedin"></i> LinkedIn:</h6> <%= link_to @user.linkedin, @user.linkedin_url %></li>
          <% end %>
          
          <% if @user.website.present? %>
            <li><h6><i class="icon-globe"></i> Website:</h6> <%= link_to @user.website, @user.website %></li>
          <% end %>
        </ul>

        <a href="/" class="pull-right"><i class="icon-arrow-left"></i>Back</a>
      </div>
    </div>

  </div>
</div>

app/views/users/why.html.erb
<div class="row">
  <div class="span12">
    <h3>What's this all about?</h3>
    <p class="lead">This is who we are. So many different faces make up this active, brilliant, and (surprisingly) small community. <%= @site_title %> is a proud announcement of membership in that community.</p>
    
    <p class="lead">It also helps us all stay connected:</p>

    <div class="row">
      <div class="span6">
        <h4 class="title-bg">Building Relationships</h4>
        <p>Browse <%= @site_title %> on Monday. Three days later, you run into someone you found interesting and say "Hello". Coffee happens. Project happens. Magic!</p>
      </div>
      <div class="span6">
        <h4 class="title-bg">Ambient Familiarity&trade;</h4>
        <p>So you're out and about, and you see someone you recognize. Can't place the name? It happens to all of us. Next time, skim <%= @site_title %> and strike up a conversation.</p>
      </div>
      
      <div class="span12">
        <%#= Feel free to add your own image below. %>
        <%#= image_tag "omaha.jpg" %>
      </div>
    </div>
  </div> 
</div>

</div> <!-- End Container -->

<style type="text/css" media="screen">
  p{
    font-size: 16px;
    line-height: 1.5;
  }
</style>