config/routes.rb
Omawho::Application.routes.draw do
  resources :events, :except => :show do
    post 'attend' => 'events#attend', :as => :attend
    put 'approve' => 'events#approve', :as => :approve
  end
  
  match 'why' => 'users#why', :as => :why
  match 'beta' => 'users#beta', :as => :beta
  
  match 'profile' => 'users#edit', :as => :profile
  
  resources :images, :except => :show

  resources :password_resets
  resources :user_sessions
  resources :users, :except => :show
  
  match 'add' => 'users#new', :as => :signup
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'event/:event' => 'users#index', :as => :event
  match 'category/:category' => 'users#index', :as => :category
  
  match '/feed' => 'users#feed', :as => :feed, :defaults => {:format => 'atom'}
  root :to => 'users#index'
  
  match ':username' => 'users#show', :as => :view_profile
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :location, :name, :link, :venue
  
  has_and_belongs_to_many :users
  
  scope :approved, where(:approved => true)
  
  validates_presence_of :date
  validates_presence_of :location
  validates_presence_of :name
  
  before_save :generate_slug
  
  def generate_slug
    self.slug = "#{name.parameterize}-#{date.year}-#{date.month}-#{date.day}"
  end
  
  def is_current
    self.date > Time.now
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :require_login, :except => [:edit, :update, :destroy]
  
  def attend
    @event = Event.find(params[:event_id])
    
    if current_user.events.exists?(@event)
      current_user.events.delete(@event)
    else
      current_user.events << @event
    end
    
    @user_events = current_user.events
    
    respond_to do |format|
      format.html { redirect_to event_path(@event.slug), notice: 'Your attendance status was updated.' }
      format.json { render json: @events }
      format.js
    end
  end
  
  # GET /events
  # GET /events.json
  def index
    if current_user && current_user.admin?
      @events = Event.where('date > ?', DateTime.now).order("date ASC")
      @past_events = Event.where('date < ?', DateTime.now).order("date DESC")
    else
      @events = Event.approved.where('date > ?', DateTime.now).order("date ASC")
      @past_events = Event.approved.where('date < ?', DateTime.now).order("date DESC")
    end
    
    if current_user
      @user_events = current_user.events
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    if current_user.admin?
      @event = Event.find(params[:id])
    else
      not_authenticated
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to :events, notice: 'Request to add event received.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    if current_user.admin?
      @event = Event.find(params[:id])

      respond_to do |format|
        if @event.update_attributes(params[:event])
          format.html { redirect_to event_path(@event.slug), notice: 'Event was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    else
      not_authenticated
    end
  end
  
  def approve
    if current_user.admin?
      @event = Event.find(params[:event_id])

      respond_to do |format|
        if @event.update_attribute(:approved, true)
          format.html { redirect_to :events, notice: 'Event approved.' }
          format.json { head :no_content }
        else
          format.html { redirect_to :events, alert: 'Error.' }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    else
      not_authenticated
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    if current_user.admin?
      @event = Event.find(params[:id])
      @event.destroy

      respond_to do |format|
        format.html { redirect_to events_url }
        format.json { head :no_content }
      end
    else
      not_authenticated
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= form_errors @event, "Event" %>

  <%= f.text_field :name, :placeholder => "Event Name" %><br />

  <%= f.datetime_select :date, {:ampm => true, :start_year => Time.now.year, :end_year => Time.now.year + 3, :default => {:hour => 12, :minute => 00}, :use_short_month => true, :order => [:month, :day, :year], :discard_hour => true}, {:class => "input-small"} %><br />

  <%= f.text_field :venue, :placeholder => "Venue (optional)" %><br />
  
  <%= f.text_field :location, :placeholder => "City" %><br />

  <%= f.text_field :link, :placeholder => "Website (optional)" %><br />

  <p><%= f.submit "Submit Event", :class => "btn" %></p>
<% end %>

app/views/events/_row.html.erb
<td>
  <h5><%= link_to event.name, event_path(event.slug) %></h5>
  <%= event.date.to_s(:full) %>
</td>
<td class="event_location">
  <%= content_tag("span", event.venue, :class => "venue") if event.venue.present? %>
  <small class="muted"><%= event.location %></small>
</td>
<td>
  <% if event.link.present? %>
    <%= link_to "Event Website", event.link, :class => "btn btn-mini btn-link" %>
  <% end %>
</td>

<% if event.approved? %>
  <td><%= link_to "#{event.users.count} #{event.is_current ? "attending" : "attended"}", event_path(event.slug), :class => "btn btn-mini" %></td>

  <% if current_user %>
    <td>
      <% if event.is_current %>
        <%= form_tag event_attend_path(event.id), :remote => true, :class => "event_row_form" do %>
          <% if @user_events.exists?(event) %>
            <%= button_tag "Cancel Your Attendance", :type => "submit", :class => "btn btn-danger btn-mini attend_event" %>
          <% else %>
            <%= button_tag "Attend", :type => "submit", :class => "btn btn-primary btn-mini attend_event" %>
          <% end %>
      
          <%= image_tag("loading.gif", :alt => "Loading...", :class => "event_row_loading", :style => "display: none") %>
        <% end %>
      <% else %>
        &nbsp;
      <% end %>
    </td>
  <% else %>
    <td>
      <%= link_to "Log in to mark your attendance.", login_path(:return_to_url => event_path(event.slug)), :class => "btn btn-primary btn-mini" %>
    </td>
  <% end %>
<% else %>
  <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <td><%= link_to 'Approve', event_approve_path(event.id), method: :put %></td>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row">
  <div class="span12">
    <h1>Events</h1>
    
    <p><%= link_to "Submit Event", :new_event, :class => "btn btn-inverse btn-small" %></p>
    
    <table id="events_table" class="table table-striped table-condensed">
      <tbody>
        <% @events.each do |event| %>
          <tr id="<%= "event_row_#{event.id}" %>">
            <%= render :partial => "row", :locals => {:event => event, :current => true} %>
          </tr>
        <% end %>
      </tbody>
      
      <tbody class="past_events">
        <% @past_events.each do |event| %>
          <tr id="<%= "event_row_#{event.id}" %>">
            <%= render :partial => "row", :locals => {:event => event, :current => false} %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<style type="text/css" media="screen">
  h5{
    margin: 0;
    padding: 0;
    line-height: 20px;
  }
  p{
    font-size: 16px;
    line-height: 1.5;
  }
  form{
    margin-bottom: 0;
  }
</style>

app/views/events/new.html.erb
<div class="row">
  <div class="span12">
    <h1>Submit Event</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<!-- Page Content
================================================== --> 
<div class="row" id="omawho_event">

  <!-- Gallery Items
  ================================================== --> 
  <div class="span12 gallery">
    
    <h4 id="event_header"><%= @event.name %></h4>
    <h5>
      <%= @event.date.to_s(:full) %><br />
      
      <% if @event.venue.present? %>
        <%= @event.venue %><br />
      <% end %>
      
      <span class="event_city muted"><%= @event.location %></span>
    </h5>
    
    <% if !current_user %>
      <p><%= link_to "Log in to mark your attendance.", login_path(:return_to_url => event_path(@event.slug)), :class => "btn btn-primary btn-mini" %></p>
    <% end %>
    
    <% if current_user && @event.is_current %>
      <%= form_tag event_attend_path(@event.id) do %>
        <% if @event.link.present? %>
          <%= link_to "Event Website", @event.link, :class => "btn btn-mini" %>
        <% end %>&nbsp;
        
        <% if current_user.events.exists?(@event) %>
          <%= button_tag "Cancel Your Attendance", :type => "submit", :class => "btn btn-danger btn-mini" %>
        <% else %>
          <%= button_tag "Attend", :type => "submit", :class => "btn btn-primary btn-mini" %>
        <% end %>
      <% end %>
    <% end %>
    
    <hr />
    
    <% if @event_categories.length > 0 %>
      <ul id="filterOptions" class="gallery-cats clearfix">
        <li class="active"><a href="#" class="all">All</a></li> 
      
        <% @event_categories.each do |k, v| %>
          <li><a href="#" class="<%= k %>"><%= v %></a></li>
        <% end %>
      </ul>
    <% end %>

    <div class="row clearfix" id="faces">
      <ul class="gallery-post-grid holder <%= "quiz" if @quiz %>">
        
        <% if @users.length > 0 %>
          <% @users.each do |user| %>
            <% if user.image %>
              <li  class="span3 gallery-item" data-id="id-<%= user.id %>" data-type="<%= user.category %>">
                <%= link_to "", view_profile_path(user.username), :class => "gallery-hover-4col hidden-phone hidden-tablet quiz_link" %>
                <%= link_to image_tag(user.image.file.square, :alt => user.name), view_profile_path(user.username), :class => "quiz_link" %>
                <span class="project-details">
                  <%= link_to user.name, view_profile_path(user.username), :class => "user_name" %>
                  <%= User::CATEGORIES[user.category] %>
                </span>
              </li>
            <% end %>
          <% end %>
        <% else %>
          <div class="span12">
            <h5>Bummer, no one's attending this event yet.</h5>
          </div>
        <% end %>

      </ul>
    </div>

  </div><!-- End gallery list-->

</div><!-- End container row -->