config/routes.rb
Omawho::Application.routes.draw do
  resources :events, :except => :show do
    post 'attend' => 'events#attend', :as => :attend
    put 'approve' => 'events#approve', :as => :approve
  end
  
  match 'why' => 'users#why', :as => :why
  match 'beta' => 'users#beta', :as => :beta
  
  match 'profile' => 'users#edit', :as => :profile
  
  resources :images, :except => :show

  resources :password_resets
  resources :user_sessions
  resources :users, :except => :show
  
  match 'add' => 'users#new', :as => :signup
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'event/:event' => 'users#index', :as => :event
  match 'category/:category' => 'users#index', :as => :category
  
  match '/feed' => 'users#feed', :as => :feed, :defaults => {:format => 'atom'}
  root :to => 'users#index'
  
  match ':username' => 'users#show', :as => :view_profile
end

app/views/layouts/_footer.html.erb
<div class="footer-container"><!-- Begin Footer -->
  <div class="container">
    <div class="row"><!-- Begin Sub Footer -->
      <div class="span12 footer-col footer-sub">
        <div class="row no-margin">
          <div class="span6"><span class="left"><%= link_to image_tag("bwb.png", :alt => "Big Wheel Brigade", :id => "bwb"), "http://bigwheelbrigade.com" %> Brought to you by <a href="http://bigwheelbrigade.com">Big Wheel Brigade</a>.</span></div>
          <div class="span6">
            <span class="right">
              <a href="/"><%= @site_title %></a>
            </span>
          </div>
        </div>
      </div>
    </div><!-- End Sub Footer -->
  </div>
</div><!-- End Footer -->

<style type="text/css" media="screen">
  .footer-container{
    position: relative;
  }
</style>

app/views/layouts/_form_errors.html.erb
<% if form_model.errors.any? %>
	<div class="alert alert-block alert-error">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	
    <% form_model.errors.full_messages.each do |msg| %>
			<%= msg %>.<br />
    <% end %>
	</div>
<% end %>

app/views/layouts/_nav.html.erb
<div class="span7 navigation">
  <div class="navbar hidden-phone">

    <ul class="nav" id="omawho_nav">
      <% if current_user %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="<%= profile_path %>">Your Face <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Face", :profile %></li>
            <li><%= link_to "Logout", :logout %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Add Your Face", :signup %></li>
        <li><%= link_to "Login", :login %></li>
      <% end %>
      
      <li><%= link_to "Events", :events %></li>
      <li><%= link_to "About", :why %></li>
      
      <% if !@site_twitter.blank? %>
        <li class="last"><a href="http://twitter.com/<%= @site_twitter %>"><i class="icon-twitter"></i></a></li>
      <% end %>
      
      <li id="facebook_thing">
        <div class="fb-like" data-href="<%= @site_url %>" data-send="false" data-layout="button_count" data-width="145" data-show-faces="false"></div>
      </li>
    </ul>

  </div>

  <!-- Mobile Nav
  ================================================== -->
  <form action="#" id="mobile-nav" class="visible-phone">
    <div class="mobile-nav-select">
      <select onchange="window.open(this.options[this.selectedIndex].value,'_top')">
        <optgroup label="<%= @site_title %>">
          <option value="">Navigate...</option>
          
          <% if current_user %>
            <%= content_tag "option", "Edit Face", :value => profile_path %>
            <%= content_tag "option",  "Logout", :value => logout_path %>
          <% else %>
            <%= content_tag "option",  "Add Your Face", :value => signup_path %>
            <%= content_tag "option",  "Login", :value => login_path %>
          <% end %>
        </optgroup>
        
        <optgroup label="Categories">
          <%= content_tag "option",  "All", :value => root_path %>
          
          <% @all_active_categories.each do |k, v| %>
            <%= content_tag "option",  v, :value => category_path(k) %>
          <% end %>
        </optgroup>
        
        <optgroup label="More">
          <%= content_tag "option",  "Events", :value => events_path %>
          <%= content_tag "option",  "About", :value => why_path %>
        </optgroup>
      </select>
    </div>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title><%= page_title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <meta name="description" content="<%= page_description %>">  
  <meta property="og:image" content="<%= "#{request.protocol}#{request.host_with_port}#{asset_path('omawho-share.png')}" %>" />

  <!-- CSS
  ================================================== -->
  <link href="http://fonts.googleapis.com/css?family=Arvo|Signika:700" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- Favicons
  ================================================== -->
  <link rel="shortcut icon" href="<%= asset_path("icons/favicon.ico") %>">
  <link rel="apple-touch-icon" href="<%= asset_path("icons/apple-touch-icon.png") %>">
  <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path("icons/apple-touch-icon-72x72.png") %>">
  <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path("icons/apple-touch-icon-114x114.png") %>">
  <link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path("icons/apple-touch-icon-144x144.png") %>" />

  <!-- JS
  ================================================== -->
  <%= javascript_include_tag "application" %>
  
  <%= auto_discovery_link_tag :atom, "/feed" %>
  <%= auto_discovery_link_tag :rss, "/feed.rss" %>

  <%= csrf_meta_tags %>
</head>

<body class="home">

  <!-- Color Bars (above header)-->
  <div class="color-bar-1"></div>
  <div class="color-bar-2 color-bg"></div>

  <div class="container">
    <div class="row header"><!-- Begin Header -->

      <!-- Logo
      ================================================== -->
      <div class="span5 logo">
        <%= link_to @site_title, :root %>
      </div>

      <!-- Main Navigation
      ================================================== -->
      <%= render :partial => "layouts/nav", :locals => {} %>
      
      <div class="span12" id="blurb">
        <h2><%= blurb %></h2>
      </div>
    </div><!-- End Header -->

    <!-- Page Content
    ================================================== --> 
    <% if notice.present? || alert.present? %>
      <div class="alert <%= notice.present? ? "alert-success" : "alert-error" %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        
        <% if notice.present? %>
          <i class="icon-ok"></i> <%= notice %>
        <% else %>
          <i class="icon-exclamation-sign"></i> <%= alert %>
        <% end %>          
      </div>
    <% end %>
    
    <%= yield %>
    
  </div> <!-- End Container -->

  <!-- Footer Area
  ================================================== -->
  <%= render :partial => "layouts/footer", :locals => {} %>

  <!-- Scroll to Top -->  
  <div id="toTop" class="hidden-phone hidden-tablet">Back to Top</div>
    
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.async = true;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>